### ISSUE TITLE
getAuthToken not supported

### ISSUE THREAD

**Issue by jberkel** [jberkel/sms-backup-plus#394]
```
java.lang.RuntimeException: An error occured while executing doInBackground()
at android.os.AsyncTask$3.done(AsyncTask.java:299)
at java.util.concurrent.FutureTask$Sync.innerSetException(FutureTask.java:273)
at java.util.concurrent.FutureTask.setException(FutureTask.java:124)
at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:307)
at java.util.concurrent.FutureTask.run(FutureTask.java:137)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
at java.lang.Thread.run(Thread.java:864) Caused by: java.lang.IllegalArgumentException: getAuthToken not supported
at android.accounts.AccountManager.convertErrorToException(AccountManager.java:1609)
at android.accounts.AccountManager.access$400(AccountManager.java:140)
at android.accounts.AccountManager$AmsTask$Response.onError(AccountManager.java:1458)
at android.accounts.IAccountManagerResponse$Stub.onTransact(IAccountManagerResponse.java:69)
at android.os.Binder.execTransact(Binder.java:367)
at dalvik.system.NativeStart.run(Native Method) java.lang.IllegalArgumentException: getAuthToken not supported
at android.accounts.AccountManager.convertErrorToException(AccountManager.java:1609)
at android.accounts.AccountManager.access$400(AccountManager.java:140)
at android.accounts.AccountManager$AmsTask$Response.onError(AccountManager.java:1458)
at android.accounts.IAccountManagerResponse$Stub.onTransact(IAccountManagerResponse.java:69)
at android.os.Binder.execTransact(Binder.java:367)
at dalvik.system.NativeStart.run(Native Method)
```

**Comment by timepp** [comment]
what's the reason? I met the same problem
