### ISSUE TITLE
crashing after upgrade from 1.5.6-beta5 to 1.5.8

### ISSUE THREAD

**Issue by nomwerp** [jberkel/sms-backup-plus#525]
any idea?

```
I/Timeline(  927): Timeline: Activity_launch_request id:com.zegoggles.smssync time:40687
I/ActivityManager(  588): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.zegoggles.smssync/.activity.MainActivity} from pid 927
I/ActivityManager(  588): Start proc com.zegoggles.smssync for activity com.zegoggles.smssync/.activity.MainActivity: pid=1936 uid=10067 gids={50067, 3003, 1028, 1015}
D/ActivityThread( 1936): handleBindApplication:com.zegoggles.smssync
D/SMSBackup+( 1936): onResume()
I/ActivityManager(  588): Displayed com.zegoggles.smssync/.activity.MainActivity: +546ms
I/Timeline(  588): Timeline: Activity_windows_visible id: ActivityRecord{41e698c8 u0 com.zegoggles.smssync/.activity.MainActivity t2} time:41433
D/SMSBackup+( 1936): using new contacts API
D/SMSBackup+( 1936): insecure store uri specified, trusting ALL certificates
E/AndroidRuntime( 1936): Process: com.zegoggles.smssync, PID: 1936
E/AndroidRuntime( 1936): 	at com.zegoggles.smssync.mail.BackupImapStore.<init>(BackupImapStore.java:60)
E/AndroidRuntime( 1936): 	at com.zegoggles.smssync.service.ServiceBase.getBackupImapStore(ServiceBase.java:102)
E/AndroidRuntime( 1936): 	at com.zegoggles.smssync.service.SmsBackupService.backup(SmsBackupService.java:105)
E/AndroidRuntime( 1936): 	at com.zegoggles.smssync.service.SmsBackupService.handleIntent(SmsBackupService.java:87)
E/AndroidRuntime( 1936): 	at com.zegoggles.smssync.service.ServiceBase.onStartCommand(ServiceBase.java:87)
W/ActivityManager(  588):   Force finishing activity com.zegoggles.smssync/.activity.MainActivity
W/ActivityManager(  588): Activity pause timeout for ActivityRecord{41e698c8 u0 com.zegoggles.smssync/.activity.MainActivity t2 f}
I/ActivityManager(  588): Process com.zegoggles.smssync (pid 1936) has died.
W/ActivityManager(  588): Scheduling restart of crashed service com.zegoggles.smssync/.service.SmsBackupService in 4028ms
I/WindowState(  588): WIN DEATH: Window{421f2e08 u0 com.zegoggles.smssync/com.zegoggles.smssync.activity.MainActivity}
I/ActivityManager(  588): Start proc com.zegoggles.smssync for service com.zegoggles.smssync/.service.SmsBackupService: pid=2173 uid=10067 gids={50067, 3003, 1028, 1015}
D/ActivityThread( 2173): handleBindApplication:com.zegoggles.smssync
D/SMSBackup+( 2173): using new contacts API
D/SMSBackup+( 2173): insecure store uri specified, trusting ALL certificates
E/AndroidRuntime( 2173): Process: com.zegoggles.smssync, PID: 2173
E/AndroidRuntime( 2173): 	at com.zegoggles.smssync.mail.BackupImapStore.<init>(BackupImapStore.java:60)
E/AndroidRuntime( 2173): 	at com.zegoggles.smssync.service.ServiceBase.getBackupImapStore(ServiceBase.java:102)
E/AndroidRuntime( 2173): 	at com.zegoggles.smssync.service.SmsBackupService.backup(SmsBackupService.java:105)
E/AndroidRuntime( 2173): 	at com.zegoggles.smssync.service.SmsBackupService.handleIntent(SmsBackupService.java:87)
E/AndroidRuntime( 2173): 	at com.zegoggles.smssync.service.ServiceBase.onStartCommand(ServiceBase.java:87)
I/ActivityManager(  588): Process com.zegoggles.smssync (pid 2173) has died.
W/ActivityManager(  588): Service crashed 2 times, stopping: ServiceRecord{41ea3ea8 u0 ```

**Comment by jberkel** [comment]
Somehow the crash reason is obscured in this stacktrace, is there anything else in the logs ?

**Comment by nomwerp** [comment]
sorry was filtering on "SMS" here is the full log:
issue seems to be ```Could not find class 'com.beetstra.jutf7.CharsetProvider', referenced from method com.fsck.k9.mail.store.imap.ImapStore.<init>```    this the build from f-doird maybe something went wrong there?

(crash happens when pressing "backup")
```
I/ActivityManager(  588): Start proc com.zegoggles.smssync for service com.zegoggles.smssync/.service.SmsBackupService: pid=10129 uid=10067 gids={50067, 3003, 1028, 1015}
I/dalvikvm(10129): Enabling JNI app bug workarounds for target SDK version 10...
D/ActivityThread(10129): handleBindApplication:com.zegoggles.smssync
D/ActivityThread(10129): setTargetHeapUtilization:0.75
D/ActivityThread(10129): setTargetHeapMinFree:2097152
D/SMSBackup+(10129): using new contacts API
W/dalvikvm(10129): VFY: unable to resolve static field 2284 (DEFAULT) in Lorg/apache/james/mime4j/field/address/AddressBuilder;
D/dalvikvm(10129): VFY: replacing opcode 0x62 at 0x000f
E/dalvikvm(10129): Could not find class 'com.beetstra.jutf7.CharsetProvider', referenced from method com.fsck.k9.mail.store.imap.ImapStore.<init>
W/dalvikvm(10129): VFY: unable to resolve new-instance 133 (Lcom/beetstra/jutf7/CharsetProvider;) in Lcom/fsck/k9/mail/store/imap/ImapStore;
D/dalvikvm(10129): VFY: replacing opcode 0x22 at 0x004a
D/dalvikvm(10129): DexOpt: unable to opt direct call 0x013f at 0x4c in Lcom/fsck/k9/mail/store/imap/ImapStore;.<init>
D/SMSBackup+(10129): insecure store uri specified, trusting ALL certificates
D/AndroidRuntime(10129): Shutting down VM
W/dalvikvm(10129): threadid=1: thread exiting with uncaught exception (group=0x418d9ce0)
E/AndroidRuntime(10129): FATAL EXCEPTION: main
E/AndroidRuntime(10129): Process: com.zegoggles.smssync, PID: 10129
E/AndroidRuntime(10129): java.lang.NoClassDefFoundError: com.beetstra.jutf7.CharsetProvider
E/AndroidRuntime(10129): 	at com.fsck.k9.mail.store.imap.ImapStore.<init>(ImapStore.java:356)
E/AndroidRuntime(10129): 	at com.zegoggles.smssync.mail.BackupImapStore.<init>(BackupImapStore.java:60)
E/AndroidRuntime(10129): 	at com.zegoggles.smssync.service.ServiceBase.getBackupImapStore(ServiceBase.java:102)
E/AndroidRuntime(10129): 	at com.zegoggles.smssync.service.SmsBackupService.backup(SmsBackupService.java:105)
E/AndroidRuntime(10129): 	at com.zegoggles.smssync.service.SmsBackupService.handleIntent(SmsBackupService.java:87)
E/AndroidRuntime(10129): 	at com.zegoggles.smssync.service.ServiceBase.onStartCommand(ServiceBase.java:87)
E/AndroidRuntime(10129): 	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2726)
E/AndroidRuntime(10129): 	at android.app.ActivityThread.access$2100(ActivityThread.java:144)
E/AndroidRuntime(10129): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1302)
E/AndroidRuntime(10129): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(10129): 	at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime(10129): 	at android.app.ActivityThread.main(ActivityThread.java:5146)
E/AndroidRuntime(10129): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(10129): 	at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime(10129): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:732)
E/AndroidRuntime(10129): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:566)
E/AndroidRuntime(10129): 	at dalvik.system.NativeStart.main(Native Method)
W/InputMethodManagerService(  588): Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@42bf6158 attribute=null, token = android.os.BinderProxy@41dd3260
I/Process (10129): Sending signal. PID: 10129 SIG: 9
I/ActivityManager(  588): Process com.zegoggles.smssync (pid 10129) has died.
W/ActivityManager(  588): Service crashed 2 times, stopping: ServiceRecord{42ac0ac8 u0 com.zegoggles.smssync/.service.SmsBackupService}
W/GooglePlayServicesUtil( 1056): Google Play services is missing.
```

**Comment by jberkel** [comment]
i think this is an f-droid issue: https://github.com/jberkel/sms-backup-plus/issues/523

cc @RealRancor

**Comment by nomwerp** [comment]
yes definitely looks like it, thank for looking into it.

**Comment by RealRancor** [comment]
Thanks for the notification, disabling the update for now until we found a better way to build the k9libs.

**Comment by kLeZ** [comment]
It is still happening. Anyone can provide some info on how to solve it?

**Comment by jberkel** [comment]
@kLeZ You have to uninstall and reinstall using f-droid

**Comment by kLeZ** [comment]
I'm sorry, I think it's too late and I'm confusing your words... Did you meant that re-install the package solves the problem? I use f-droid as my sole package manager, thus I've already installed smsbackup+ from there.

**Comment by RealRancor** [comment]
@kLeZ 
Yes, you need to uninstall the app on f-droid and then install it again.

**Comment by jberkel** [comment]
f-droid published a broken version, and they can't autoupdate people who are on the old version, so you have to reinstall

**Comment by jberkel** [comment]
i'm going to publish a new version soon which should fix the problem in the future (it will force updates on f-droid)
