### ISSUE TITLE
force close when trying to backup

### ISSUE THREAD

**Issue by jeekajoo** [jberkel/sms-backup-plus#531]
Hi

When trying to backup, the application crashes.

- Version: 1.5.8 from f-droid
- OS: Omnirom 4.4.4-20141111
- Phone: Nexus 5 (hammerhead)
- IMAP: with my personal IMAP server (dovecot / debian 7)
- TLS: CAcert certificates included into system certificates. Tried all combinations about SSL/TLS security settings.

It used to work on older versions:
- 1.5.6-beta5
- 1.5.6-beta4

```
D/SMSBackup+( 9429): using new contacts API
D/SMSBackup+( 9429): insecure store uri specified, trusting ALL certificates
D/AndroidRuntime( 9429): Shutting down VM
E/AndroidRuntime( 9429): FATAL EXCEPTION: main
E/AndroidRuntime( 9429): Process: com.zegoggles.smssync, PID: 9429
E/AndroidRuntime( 9429): java.lang.NoClassDefFoundError: Failed resolution of: Lcom/beetstra/jutf7/CharsetProvider;
E/AndroidRuntime( 9429): 	at com.fsck.k9.mail.store.imap.ImapStore.<init>(ImapStore.java:356)
E/AndroidRuntime( 9429): 	at com.zegoggles.smssync.mail.BackupImapStore.<init>(BackupImapStore.java:60)
E/AndroidRuntime( 9429): 	at com.zegoggles.smssync.service.ServiceBase.getBackupImapStore(ServiceBase.java:102)
E/AndroidRuntime( 9429): 	at com.zegoggles.smssync.service.SmsBackupService.backup(SmsBackupService.java:105)
E/AndroidRuntime( 9429): 	at com.zegoggles.smssync.service.SmsBackupService.handleIntent(SmsBackupService.java:87)
E/AndroidRuntime( 9429): 	at com.zegoggles.smssync.service.ServiceBase.onStartCommand(ServiceBase.java:87)
E/AndroidRuntime( 9429): 	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2688)
E/AndroidRuntime( 9429): 	at android.app.ActivityThread.access$2100(ActivityThread.java:135)
E/AndroidRuntime( 9429): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1293)
E/AndroidRuntime( 9429): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 9429): 	at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime( 9429): 	at android.app.ActivityThread.main(ActivityThread.java:5001)
E/AndroidRuntime( 9429): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 9429): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
E/AndroidRuntime( 9429): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
E/AndroidRuntime( 9429): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.beetstra.jutf7.CharsetProvider" on path: DexPathList[[zip file "/data/app/com.zegoggles.smssync-2.apk"],nativeLibraryDirectories=[/data/app-lib/com.zegoggles.smssync-2, /vendor/lib, /system/lib]]
E/AndroidRuntime( 9429): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
E/AndroidRuntime( 9429): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
E/AndroidRuntime( 9429): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
E/AndroidRuntime( 9429): 	... 15 more
E/AndroidRuntime( 9429): 	Suppressed: java.lang.ClassNotFoundException: com.beetstra.jutf7.CharsetProvider
E/AndroidRuntime( 9429): 		at java.lang.Class.classForName(Native Method)
E/AndroidRuntime( 9429): 		at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
E/AndroidRuntime( 9429): 		at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
E/AndroidRuntime( 9429): 		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
E/AndroidRuntime( 9429): 		... 16 more
E/AndroidRuntime( 9429): 	Caused by: java.lang.NoClassDefFoundError: Class "Lcom/beetstra/jutf7/CharsetProvider;" not found
E/AndroidRuntime( 9429): 		... 20 more
W/ActivityManager(  811):   Force finishing activity com.zegoggles.smssync/.activity.MainActivity
W/ActivityManager(  811): Activity pause timeout for ActivityRecord{65e80420 u0 com.zegoggles.smssync/.activity.MainActivity t73 f}
W/ActivityManager(  811): Activity destroy timeout for ActivityRecord{65e80420 u0 com.zegoggles.smssync/.activity.MainActivity t73 f}
```
Let me know if I can provide you with more information.

**Comment by jberkel** [comment]
dup of #525
