### ISSUE TITLE
StrictMode policy violation; ~duration=60 ms: android.os.StrictMode$StrictModeDiskWriteViolation: policy=2069 violation=1

### ISSUE THREAD

**Issue by haridsv** [jberkel/sms-backup-plus#557]
Just happened to notice this exception coming in logcat, and I suspect it sometimes makes the save fail. I am however not sure what causes it or how to fix it.

```
D/StrictMode( 2875): StrictMode policy violation; ~duration=60 ms: android.os.StrictMode$StrictModeDiskWriteViolation: policy=2069 violation=1
D/StrictMode( 2875): 	at android.os.StrictMode$AndroidBlockGuardPolicy.onWriteToDisk(StrictMode.java:1111)
D/StrictMode( 2875): 	at libcore.io.BlockGuardOs.remove(BlockGuardOs.java:254)
D/StrictMode( 2875): 	at java.io.File.delete(File.java:313)
D/StrictMode( 2875): 	at android.app.SharedPreferencesImpl.writeToFile(SharedPreferencesImpl.java:611)
D/StrictMode( 2875): 	at android.app.SharedPreferencesImpl.access$800(SharedPreferencesImpl.java:51)
D/StrictMode( 2875): 	at android.app.SharedPreferencesImpl$2.run(SharedPreferencesImpl.java:512)
D/StrictMode( 2875): 	at android.app.SharedPreferencesImpl.enqueueDiskWrite(SharedPreferencesImpl.java:533)
D/StrictMode( 2875): 	at android.app.SharedPreferencesImpl.access$100(SharedPreferencesImpl.java:51)
D/StrictMode( 2875): 	at android.app.SharedPreferencesImpl$EditorImpl.commit(SharedPreferencesImpl.java:455)
D/StrictMode( 2875): 	at com.zegoggles.smssync.preferences.Preferences.setReferenceUid(Preferences.java:122)
D/StrictMode( 2875): 	at com.zegoggles.smssync.mail.MessageConverter.<init>(MessageConverter.java:78)
D/StrictMode( 2875): 	at com.zegoggles.smssync.service.BackupTask.<init>(BackupTask.java:69)
D/StrictMode( 2875): 	at com.zegoggles.smssync.service.SmsBackupService.getBackupTask(SmsBackupService.java:168)
D/StrictMode( 2875): 	at com.zegoggles.smssync.service.SmsBackupService.backup(SmsBackupService.java:105)
D/StrictMode( 2875): 	at com.zegoggles.smssync.service.SmsBackupService.handleIntent(SmsBackupService.java:87)
D/StrictMode( 2875): 	at com.zegoggles.smssync.service.ServiceBase.onStartCommand(ServiceBase.java:87)
D/StrictMode( 2875): 	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2897)
D/StrictMode( 2875): 	at android.app.ActivityThread.access$2100(ActivityThread.java:151)
D/StrictMode( 2875): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1401)
D/StrictMode( 2875): 	at android.os.Handler.dispatchMessage(Handler.java:102)
D/StrictMode( 2875): 	at android.os.Looper.loop(Looper.java:135)
D/StrictMode( 2875): 	at android.app.ActivityThread.main(ActivityThread.java:5257)
D/StrictMode( 2875): 	at java.lang.reflect.Method.invoke(Native Method)
D/StrictMode( 2875): 	at java.lang.reflect.Method.invoke(Method.java:372)
D/StrictMode( 2875): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
D/StrictMode( 2875): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
```

**Comment by jberkel** [comment]
this is just a warning and can be ignored. should not show up in the logs though.
