### ISSUE TITLE
App crash (f-droid)

### ISSUE THREAD

**Issue by Mageti** [jberkel/sms-backup-plus#574]
Hello,
SMS-backup+ crashes when I ask him to backup my SMS. It used to work correctly, but not now anymore.
Here are some informations :
- Android version 4.1.2 on Wiko Cink Peax 2
- SMS Backup+ v1.5.8 from f-droid
- I have ~11000 messages on stock SMS app
- I backup on my own IMAP server
Log :
```
E/Trace   (18351): error opening trace file: No such file or directory (2)
W/dalvikvm(18351): VFY: unable to resolve static method 234: Landroid/provider/Telephony$Sms;.getDefaultSmsPackage (Landroid/content/Context;)Ljava/lang/String;
W/dalvikvm(18351): VFY: unable to resolve static method 234: Landroid/provider/Telephony$Sms;.getDefaultSmsPackage (Landroid/content/Context;)Ljava/lang/String;
I/System  (18191): libcore.io.ErrnoException: kill failed: EPERM (Operation not permitted)
I/System  (18191): 	at libcore.io.Posix.kill(Native Method)
I/System  (18191): 	at libcore.io.ForwardingOs.kill(ForwardingOs.java:77)
I/System  (18191): 	at java.lang.ProcessManager$ProcessImpl.destroy(ProcessManager.java:260)
I/System  (18191): 	at eu.chainfire.libsuperuser.Shell$Interactive.kill(Shell.java:1611)
I/System  (18191): 	at rs.pedjaapps.alogcatroot.app.LogCat.stop(LogCat.java:162)
I/System  (18191): 	at rs.pedjaapps.alogcatroot.app.LogActivity.onStop(LogActivity.java:211)
I/System  (18191): 	at android.app.Instrumentation.callActivityOnStop(Instrumentation.java:1210)
I/System  (18191): 	at android.app.Activity.performStop(Activity.java:5158)
I/System  (18191): 	at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:3128)
I/System  (18191): 	at android.app.ActivityThread.handleStopActivity(ActivityThread.java:3177)
I/System  (18191): 	at android.app.ActivityThread.access$900(ActivityThread.java:149)
I/System  (18191): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1332)
I/System  (18191): 	at android.os.Handler.dispatchMessage(Handler.java:99)
I/System  (18191): 	at android.os.Looper.loop(Looper.java:153)
I/System  (18191): 	at android.app.ActivityThread.main(ActivityThread.java:5000)
I/System  (18191): 	at java.lang.reflect.Method.invokeNative(Native Method)
I/System  (18191): 	at java.lang.reflect.Method.invoke(Method.java:511)
I/System  (18191): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:821)
I/System  (18191): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:584)
I/System  (18191): 	at dalvik.system.NativeStart.main(Native Method)
W/dalvikvm(18351): VFY: unable to resolve static method 234: Landroid/provider/Telephony$Sms;.getDefaultSmsPackage (Landroid/content/Context;)Ljava/lang/String;
W/dalvikvm(18351): VFY: unable to resolve static field 2284 (DEFAULT) in Lorg/apache/james/mime4j/field/address/AddressBuilder;
E/dalvikvm(18351): Could not find class 'com.beetstra.jutf7.CharsetProvider', referenced from method com.fsck.k9.mail.store.imap.ImapStore.<init>
W/dalvikvm(18351): VFY: unable to resolve new-instance 133 (Lcom/beetstra/jutf7/CharsetProvider;) in Lcom/fsck/k9/mail/store/imap/ImapStore;
E/AndroidRuntime(18351): FATAL EXCEPTION: main
E/AndroidRuntime(18351): java.lang.NoClassDefFoundError: com.beetstra.jutf7.CharsetProvider
E/AndroidRuntime(18351): 	at com.fsck.k9.mail.store.imap.ImapStore.<init>(ImapStore.java:356)
E/AndroidRuntime(18351): 	at com.zegoggles.smssync.mail.BackupImapStore.<init>(BackupImapStore.java:60)
E/AndroidRuntime(18351): 	at com.zegoggles.smssync.service.ServiceBase.getBackupImapStore(ServiceBase.java:102)
E/AndroidRuntime(18351): 	at com.zegoggles.smssync.service.SmsBackupService.backup(SmsBackupService.java:105)
E/AndroidRuntime(18351): 	at com.zegoggles.smssync.service.SmsBackupService.handleIntent(SmsBackupService.java:87)
E/AndroidRuntime(18351): 	at com.zegoggles.smssync.service.ServiceBase.onStartCommand(ServiceBase.java:87)
E/AndroidRuntime(18351): 	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2643)
E/AndroidRuntime(18351): 	at android.app.ActivityThread.access$1900(ActivityThread.java:149)
E/AndroidRuntime(18351): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1402)
E/AndroidRuntime(18351): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(18351): 	at android.os.Looper.loop(Looper.java:153)
E/AndroidRuntime(18351): 	at android.app.ActivityThread.main(ActivityThread.java:5000)
E/AndroidRuntime(18351): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(18351): 	at java.lang.reflect.Method.invoke(Method.java:511)
E/AndroidRuntime(18351): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:821)
E/AndroidRuntime(18351): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:584)
E/AndroidRuntime(18351): 	at dalvik.system.NativeStart.main(Native Method)
E/AppErrorDialog(  393): Failed to get ILowStorageHandle instance
E/JavaBinder(  393): !!! FAILED BINDER TRANSACTION !!!
E/JavaBinder(  393): !!! FAILED BINDER TRANSACTION !!!
```

**Comment by jberkel** [comment]
some of f-droid's version are broken, and 1.5.9 is not published there yet.
@RealRancor anything i can do to help to get a new version out?

**Comment by RealRancor** [comment]
@jberkel Thanks for the notification. Seems some one already opened an merge request for the new update: https://gitlab.com/fdroid/fdroiddata/merge_requests/893

**Comment by jberkel** [comment]
@RealRancor ah ok. i somehow assumed the process was automated, at least partially. so whenever i publish a new version i need to open a merge request on gitlab?

**Comment by RealRancor** [comment]
@jberkel Depends on the build receipt. Currently the k9lib dependency needs to be updated manually so thats probably the reason why its not set to auto-update. But maybe @krt16s can give you some more background info.

**Comment by jberkel** [comment]
@RealRancor OK. but i'm unclear where f-droids "build everything from source" philopsophy ends? if an artifact is hosted on maven central it surely won't have to be build from source each time?

**Comment by RealRancor** [comment]
I don't know the reason of the dependency but will have a look in a few days if the build receipt can be changed to only use your pom.xml

**Comment by jberkel** [comment]
@Mageti there's a new version on f-droid now, please upgrade and test again with 1.5.9

**Comment by Mageti** [comment]
Just tested that, and it works.
Thank you very much !

**Comment by herbsmn** [comment]
thanks @jberkel! i really appreciate your dilligence to get this fixed!
